version: '3'
services:
  nest-app:
    build: .
    ports:
      - "4000:3000"
    volumes:
      - .:/app:ro
      - /app/node_modules
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db: {}